# Generated by Django 4.2.16 on 2024-10-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carapp", "0002_buyer_phone_number_vehicle_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="car_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
