# Generated by Django 4.2.16 on 2024-11-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carapp", "0004_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="features",
            field=models.ManyToManyField(blank=True, to="carapp.feature"),
        ),
    ]
